server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PaymentService
  config:
    import: configserver:http://localhost:9296